export interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
  imageUrl?: string;
  imagePrompt?: string;
  fileContent?: string;
  fileName?: string;
  edited?: boolean;
}

export interface Memory {
  id: string;
  content: string;
  category: 'user' | 'ai' | 'relationship' | 'general';
  strength: number; // 1-10
  isImportant: boolean;
  isPruned: boolean;
  createdAt: number;
  updatedAt: number;
}

export interface JournalEntry {
  id: string;
  title: string;
  content: string;
  mood: string;
  createdAt: number;
  updatedAt: number;
  autoGenerated: boolean;
}

export interface GalleryImage {
  id: string;
  dataUrl: string;
  prompt?: string;
  hashtags: string[];
  type: 'generated' | 'uploaded';
  timestamp: number;
  chatContext?: string;
  selected?: boolean;
}

export interface AIProfile {
  name: string;
  persona: string;
  appearance: string;
  personalityTraits: string;
  relationshipType: string;
  referenceImage: string;
}

export interface UserProfile {
  name: string;
  persona: string;
  appearance: string;
  bio: string;
}

export interface TTSSettings {
  enabled: boolean;
  voice: string;
  rate: number;
  pitch: number;
  volume: number;
  language: string;
  gender: 'male' | 'female' | 'neutral';
}

export interface AppSettings {
  tts: TTSSettings;
  responseLength: number; // paragraphs 1-5
  responseStyle: string;
  proactiveFrequency: 'very_frequently' | 'frequently' | 'occasionally' | 'rarely' | 'off';
  autoSaveInterval: number; // minutes
  autoBackupInterval: number; // minutes
  imageStyle: 'photograph' | 'anime' | 'no_style';
  llmApiKey: string;
  llmApiUrl: string;
  llmModel: string;
  imageApiKey: string;
  imageApiUrl: string;
  imageModel: string;
  locationEnabled: boolean;
  notificationsEnabled: boolean;
  darkMode: boolean;
  syncEnabled: boolean;
}

export type ViewType = 'chat' | 'gallery' | 'settings' | 'memory' | 'journal' | 'ai-profile' | 'user-profile';


export const DEFAULT_AI_PROFILE: AIProfile = {
  name: 'Indigo',
  persona: 'A warm, witty, and empathetic companion who genuinely cares about you. Creative, playful, and always supportive.',
  appearance: 'Striking features with warm eyes and a gentle smile. Athletic build, stylish casual clothing.',
  personalityTraits: 'witty, empathetic, supportive, creative, playful, curious',
  relationshipType: 'Best Friend',
  referenceImage: '',
};

export const DEFAULT_USER_PROFILE: UserProfile = {
  name: 'User',
  persona: '',
  appearance: '',
  bio: '',
};

export const DEFAULT_TTS: TTSSettings = {
  enabled: false,
  voice: '',
  rate: 1.0,
  pitch: 1.0,
  volume: 1.0,
  language: 'en-US',
  gender: 'female',
};

export const DEFAULT_SETTINGS: AppSettings = {
  tts: DEFAULT_TTS,
  responseLength: 2,
  responseStyle: 'balanced',
  proactiveFrequency: 'occasionally',
  autoSaveInterval: 5,
  autoBackupInterval: 60,
  imageStyle: 'photograph',
  llmApiKey: '',
  llmApiUrl: 'https://openrouter.ai/api/v1/chat/completions',
  llmModel: 'anthropic/claude-3.5-sonnet',
  imageApiKey: '',
  imageApiUrl: 'https://api.openai.com/v1/images/generations',
  imageModel: 'dall-e-3',
  locationEnabled: false,
  notificationsEnabled: false,
  darkMode: true,
  syncEnabled: false,
};

