import React, { useState } from 'react';
import { useApp, JournalEntry } from '../context/AppContext';
import { GoogleGenAI } from "@google/genai";
import { Sparkles, Trash2, Edit2, Save, X } from 'lucide-react';

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

const JournalScreen: React.FC = () => {
  const { journal, addJournalEntry, updateJournalEntry, deleteJournalEntry, aiProfile, userProfile, chatHistory } = useApp();
  const [newEntry, setNewEntry] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [editingEntryId, setEditingEntryId] = useState<string | null>(null);
  const [editContent, setEditContent] = useState('');

  const handleSave = () => {
    if (!newEntry.trim()) return;
    addJournalEntry({
        id: Date.now().toString() + Math.random().toString(36).substr(2, 9),
        date: new Date().toLocaleString(),
        content: newEntry,
        isAutoGenerated: false,
    });
    setNewEntry('');
  };

  const startEditing = (entry: JournalEntry) => {
    setEditingEntryId(entry.id);
    setEditContent(entry.content);
  };

  const saveEdit = (id: string) => {
    if (!editContent.trim()) return;
    updateJournalEntry(id, { content: editContent });
    setEditingEntryId(null);
  };

  const handleDelete = (id: string) => {
    if (window.confirm("Are you sure you want to delete this journal entry?")) {
      deleteJournalEntry(id);
    }
  };

  const handleGenerateReflection = async () => {
    setIsGenerating(true);
    try {
        const recentChat = chatHistory.slice(-10).map(m => `${m.role}: ${m.content}`).join('\n');
        const prompt = `
            As ${aiProfile.name}, write a personal journal entry reflecting on your recent interactions with ${userProfile.name}.
            
            Your Personality: ${aiProfile.personality}
            
            Recent Interactions:
            ${recentChat}
            
            Write in the first person. Reflect on what you learned, how you feel (if applicable), and your thoughts on the user.
        `;

        const response = await ai.models.generateContent({
            model: "gemini-3.1-pro-preview",
            contents: prompt,
        });

        const reflection = response.text;
        addJournalEntry({
            id: Date.now().toString() + Math.random().toString(36).substr(2, 9),
            date: new Date().toLocaleString(),
            content: reflection,
            isAutoGenerated: true,
        });
    } catch (error) {
        console.error("Error generating journal:", error);
        alert("Failed to generate journal entry.");
    } finally {
        setIsGenerating(false);
    }
  };

  return (
    <div className="p-6 bg-white rounded-lg shadow-md max-w-4xl mx-auto">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold text-indigo-600">Reflective Journal</h2>
        <button
            onClick={handleGenerateReflection}
            disabled={isGenerating}
            className="flex items-center px-4 py-2 bg-indigo-100 text-indigo-700 rounded-md hover:bg-indigo-200 transition-colors disabled:opacity-50"
        >
            <Sparkles className="w-4 h-4 mr-2" />
            {isGenerating ? 'Reflecting...' : 'Generate Reflection'}
        </button>
      </div>

      <div className="mb-8 bg-gray-50 p-4 rounded-lg border border-gray-200">
        <textarea
          value={newEntry}
          onChange={(e) => setNewEntry(e.target.value)}
          rows={3}
          className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 bg-white"
          placeholder="Write your own entry..."
        />
        <div className="flex justify-end mt-2">
            <button
            onClick={handleSave}
            disabled={!newEntry.trim()}
            className="bg-indigo-600 text-white px-4 py-2 rounded-md hover:bg-indigo-700 transition-colors disabled:opacity-50"
            >
            Save Entry
            </button>
        </div>
      </div>

      <div className="space-y-6">
        {journal?.map((entry) => (
          <div key={entry.id} className={`p-6 rounded-lg border group ${entry.isAutoGenerated ? 'bg-indigo-50 border-indigo-100' : 'bg-white border-gray-200'}`}>
            <div className="flex justify-between items-start mb-2">
                <div className="flex flex-col">
                    <span className="text-xs font-medium text-gray-500 uppercase tracking-wider">{entry.date}</span>
                    {entry.isAutoGenerated && (
                        <span className="mt-1 bg-indigo-200 text-indigo-800 text-[10px] px-2 py-0.5 rounded-full flex items-center w-fit">
                            <Sparkles className="w-3 h-3 mr-1" /> AI Reflection
                        </span>
                    )}
                </div>
                <div className="flex space-x-2 transition-opacity">
                    {editingEntryId === entry.id ? (
                        <>
                            <button onClick={() => saveEdit(entry.id)} className="p-1 text-green-600 hover:text-green-700" title="Save">
                                <Save className="w-4 h-4" />
                            </button>
                            <button onClick={() => setEditingEntryId(null)} className="p-1 text-gray-400 hover:text-gray-600" title="Cancel">
                                <X className="w-4 h-4" />
                            </button>
                        </>
                    ) : (
                        <>
                            <button onClick={() => startEditing(entry)} className="p-1 text-gray-400 hover:text-indigo-600" title="Edit">
                                <Edit2 className="w-4 h-4" />
                            </button>
                            <button onClick={() => handleDelete(entry.id)} className="p-1 text-gray-400 hover:text-red-600" title="Delete">
                                <Trash2 className="w-4 h-4" />
                            </button>
                        </>
                    )}
                </div>
            </div>
            {editingEntryId === entry.id ? (
                <textarea
                    value={editContent}
                    onChange={(e) => setEditContent(e.target.value)}
                    className="w-full p-3 border border-indigo-300 rounded-md focus:ring-2 focus:ring-indigo-500 outline-none font-serif text-lg leading-relaxed"
                    rows={5}
                />
            ) : (
                <p className="text-gray-800 whitespace-pre-wrap leading-relaxed font-serif text-lg">{entry.content}</p>
            )}
          </div>
        ))}
        {journal.length === 0 && (
            <p className="text-center text-gray-400 py-8">No journal entries yet.</p>
        )}
      </div>
    </div>
  );
};

export default JournalScreen;
