export interface ChatSession {
  id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
}

export interface AIProfile {
  id: string;
  name: string;
  personality: string;
  backstory: string;
  appearance: string;
  referenceImage: string | null;
  voiceURI: string | null;
  voicePitch: number;
  voiceSpeed: number;
  autoReadMessages: boolean;
  voiceGender: 'male' | 'female' | 'none';
  responseLength: 'short' | 'medium' | 'long' | 'custom';
  responseDetail: 'low' | 'medium' | 'high' | 'standard';
  responseTone: 'friendly' | 'formal' | 'humorous' | 'serious';
  customParagraphCount: number | null;
  customWordCount: number | null;
  proactiveMessageFrequency: 'off' | 'very_frequently' | 'frequently' | 'occasionally' | 'rarely';
  model: string;
  temperature: number;
  topK: number;
  topP: number;
  timeAwareness: boolean;
  ambientMode: boolean;
  ambientFrequency: 'off' | 'very_frequently' | 'frequently' | 'occasionally' | 'rarely';
  aiCanGenerateImages: boolean;
  aiCanGenerateSpeech: boolean;
  aiCanUseTools: boolean;
  aiCanBrowse: boolean;
  chatHistory?: ChatMessage[]; // Legacy support
  sessions?: ChatSession[];
  activeSessionId?: string;
  memories?: Memory[];
  journal?: JournalEntry[];
}

export interface UserProfile {
  name: string;
  info: string;
  preferences: string;
  appearance: string;
  referenceImage: string | null;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  content: string;
  timestamp: number;
  attachments?: { type: 'image' | 'text' | 'pdf'; content: string; name: string }[];
  read?: boolean;
  groundingUrls?: { title: string; url: string }[];
}

export interface KnowledgeBaseDocument {
  name: string;
  content: string;
}

export interface Memory {
  id: string;
  content: string;
  strength: number; // 1-10
  timestamp: number;
  lastAccessed: number;
  isImportant: boolean;
}

export interface JournalEntry {
  id: string;
  date: string; // ISO string
  content: string;
  isAutoGenerated: boolean;
}

export interface GalleryItem {
  id: string;
  type: 'uploaded' | 'generated';
  url: string;
  prompt?: string;
  timestamp: number;
}
